### Pandas

* Скачайте любой табличный датасет (можете использовать тот же, что и в дз к занятию "Знакомство с библиотеками"), например, с https://www.kaggle.com/datasets
* Проведите поноценный EDA 
    * "погрузитесь" в данные
    * составьте описание измерений из датасета
    * очистите данные, если это необходимо
    * попробуйте создать дополнительные переменные, которые могут помочь лучше понять данные

In [259]:
import pandas as pd
data = pd.read_csv(r'C:\Users\Оксана\Downloads\archive\TopAnimatedImDb.csv')
'Информация о датасете', data.info, data.shape

('Информация о датасете',
 <bound method DataFrame.info of                                 Title  Rating      Votes     Gross  \
 0       Sen to Chihiro no kamikakushi     8.6    747,148   $10.06M   
 1                       The Lion King     8.5  1,041,158  $422.78M   
 2                      Hotaru no haka     8.5    272,469       NaN   
 3                      Kimi no na wa.     8.4    259,975    $5.02M   
 4   Spider-Man: Into the Spider-Verse     8.4    510,227  $190.24M   
 ..                                ...     ...        ...       ...   
 80                      Kung Fu Panda     7.6    463,897  $215.43M   
 81                              Mulan     7.6    284,542  $120.62M   
 82                 The Little Mermaid     7.6    260,026  $111.54M   
 83                    The Jungle Book     7.6    181,528  $141.84M   
 84    Snow White and the Seven Dwarfs     7.6    197,860  $184.93M   
 
                  Genre  Metascore Certificate             Director  Year  \
 0    Adven

In [260]:
data.describe()

Rating  Metascore         Year
count  85.000000  80.000000    85.000000
mean    7.922353  80.850000  2003.211765
std     0.257449   8.965616    15.255830
min     7.600000  59.000000  1937.000000
25%     7.700000  74.000000  1995.000000
50%     7.900000  82.000000  2007.000000
75%     8.100000  87.000000  2014.000000
max     8.600000  96.000000  2021.000000

In [261]:
data

Title  Rating      Votes     Gross  \
0       Sen to Chihiro no kamikakushi     8.6    747,148   $10.06M   
1                       The Lion King     8.5  1,041,158  $422.78M   
2                      Hotaru no haka     8.5    272,469       NaN   
3                      Kimi no na wa.     8.4    259,975    $5.02M   
4   Spider-Man: Into the Spider-Verse     8.4    510,227  $190.24M   
..                                ...     ...        ...       ...   
80                      Kung Fu Panda     7.6    463,897  $215.43M   
81                              Mulan     7.6    284,542  $120.62M   
82                 The Little Mermaid     7.6    260,026  $111.54M   
83                    The Jungle Book     7.6    181,528  $141.84M   
84    Snow White and the Seven Dwarfs     7.6    197,860  $184.93M   

                 Genre  Metascore Certificate             Director  Year  \
0    Adventure, Family       96.0           U       Hayao Miyazaki  2001   
1     Adventure, Drama       88.0           U         Roger Allers  1994   
2           Drama, War       94.0           U        Isao Takahata  1988   
3       Drama, Fantasy       79.0           U       Makoto Shinkai  2016   
4    Action, Adventure       87.0           U      Bob Persichetti  2018   
..                 ...        ...         ...                  ...   ...   
80   Action, Adventure       74.0           U         Mark Osborne  2008   
81   Adventure, Comedy       71.0           U        Tony Bancroft  1998   
82   Adventure, Comedy       88.0           U         Ron Clements  1989   
83   Adventure, Comedy       65.0           U  Wolfgang Reitherman  1967   
84   Adventure, Family       95.0           U     William Cottrell  1937   

                                          Description  Runtime  
0   ["\nDuring her family's move to the suburbs, a...  125 min  
1   ['\nLion prince Simba and his father are targe...   88 min  
2   ['\nA young boy and his little sister struggle...   89 min  
3   ['\nTwo strangers find themselves linked in a ...  106 min  
4   ['\nTeen Miles Morales becomes the Spider-Man ...  117 min  
..                                                ...      ...  
80  ["\nTo everyone's surprise, including his own,...   92 min  
81  ["\nTo save her father from death in the army,...   88 min  
82  ["\nA mermaid princess makes a Faustian bargai...   83 min  
83  ['\nBagheera the Panther and Baloo the Bear ha...   78 min  
84  ['\nExiled into the dangerous forest by her wi...   83 min  

[85 rows x 11 columns]

In [262]:
data['Certificate'].unique()

array(['U', 'UA', '16', '7', nan, 'PG', 'PG-13', 'Not Rated', 'A', 'R',
       '13'], dtype=object)

In [263]:
data['Gross'].unique()

array(['$10.06M', '$422.78M', nan, '$5.02M', '$190.24M', '$209.73M',
       '$223.81M', '$2.38M', '$293.00M', '$415.00M', '$191.80M',
       '$356.46M', '$4.71M', '$380.84M', '$217.58M', '$206.45M',
       '$289.92M', '$23.16M', '$1.11M', '$261.44M', '$217.35M', '$0.19M',
       '$1.00M', '$5.62M', '$48.02M', '$0.31M', '$0.77M', '$0.29M',
       '$5.21M', '$434.04M', '$189.42M', '$1.34M', '$257.76M', '$0.88M',
       '$200.82M', '$75.29M', '$7.00M', '$2.89M', '$52.04M', '$156.45M',
       '$76.41M', '$608.58M', '$248.76M', '$251.51M', '$15.09M',
       '$215.43M', '$120.62M', '$111.54M', '$141.84M', '$184.93M'],
      dtype=object)

In [264]:
data.isnull().sum() # половина сборов не известна можно анализировать там где она известна или попробовать анализировать без 

Title           0
Rating          0
Votes           0
Gross          35
Genre           0
Metascore       5
Certificate     1
Director        0
Year            0
Description     0
Runtime         0
dtype: int64

In [271]:
# Преобразовываем данные Gross к float
data = data.replace({'Gross': r'^\$'}, {'Gross': ''}, regex=True) # сначала выполним замены
data = data.replace({'Gross': r'M$'}, {'Gross': ''}, regex=True)
data['Gross'] = pd.to_numeric(data['Gross'], errors='coerce')
data['Gross']

0      10.06
1     422.78
2        NaN
3       5.02
4     190.24
       ...  
80    215.43
81    120.62
82    111.54
83    141.84
84    184.93
Name: Gross, Length: 85, dtype: float64

In [273]:
data = data.replace({'Votes': r','}, {'Votes': ''}, regex=True) # заменим , в Voits для преоброзования к int
# преобразуем данные в Voits в int
data['Votes'] = pd.to_numeric(data['Votes'], errors='coerce')
data['Votes']

0      747148
1     1041158
2      272469
3      259975
4      510227
       ...   
80     463897
81     284542
82     260026
83     181528
84     197860
Name: Votes, Length: 85, dtype: int64

In [274]:
# Преобразуем время
data = data.replace({'Runtime': r'min'}, {'Runtime': ''}, regex=True)
data['Runtime'] = pd.to_numeric(data['Runtime'], errors='coerce')
data['Runtime']

0     125
1      88
2      89
3     106
4     117
     ... 
80     92
81     88
82     83
83     78
84     83
Name: Runtime, Length: 85, dtype: int64

In [275]:
data.describe()

Rating         Votes       Gross  Metascore         Year     Runtime
count  85.000000  8.500000e+01   50.000000  80.000000    85.000000   85.000000
mean    7.922353  3.006807e+05  146.741600  80.850000  2003.211765   99.352941
std     0.257449  2.856683e+05  148.820745   8.965616    15.255830   14.637449
min     7.600000  2.531900e+04    0.190000  59.000000  1937.000000   66.000000
25%     7.700000  6.608100e+04    5.067500  74.000000  1995.000000   90.000000
50%     7.900000  1.978600e+05  131.230000  82.000000  2007.000000   99.000000
75%     8.100000  4.474470e+05  222.252500  87.000000  2014.000000  107.000000
max     8.600000  1.100175e+06  608.580000  96.000000  2021.000000  137.000000

In [276]:
# Переменуем колонки для понятия данных
data.rename(columns={"Gross": "Gross_$M"}, inplace=True)
data.rename(columns={"Runtime": "Runtime_min"}, inplace=True)
data

Title  Rating    Votes  Gross_$M  \
0       Sen to Chihiro no kamikakushi     8.6   747148     10.06   
1                       The Lion King     8.5  1041158    422.78   
2                      Hotaru no haka     8.5   272469       NaN   
3                      Kimi no na wa.     8.4   259975      5.02   
4   Spider-Man: Into the Spider-Verse     8.4   510227    190.24   
..                                ...     ...      ...       ...   
80                      Kung Fu Panda     7.6   463897    215.43   
81                              Mulan     7.6   284542    120.62   
82                 The Little Mermaid     7.6   260026    111.54   
83                    The Jungle Book     7.6   181528    141.84   
84    Snow White and the Seven Dwarfs     7.6   197860    184.93   

                 Genre  Metascore Certificate             Director  Year  \
0    Adventure, Family       96.0           U       Hayao Miyazaki  2001   
1     Adventure, Drama       88.0           U         Roger Allers  1994   
2           Drama, War       94.0           U        Isao Takahata  1988   
3       Drama, Fantasy       79.0           U       Makoto Shinkai  2016   
4    Action, Adventure       87.0           U      Bob Persichetti  2018   
..                 ...        ...         ...                  ...   ...   
80   Action, Adventure       74.0           U         Mark Osborne  2008   
81   Adventure, Comedy       71.0           U        Tony Bancroft  1998   
82   Adventure, Comedy       88.0           U         Ron Clements  1989   
83   Adventure, Comedy       65.0           U  Wolfgang Reitherman  1967   
84   Adventure, Family       95.0           U     William Cottrell  1937   

                                          Description  Runtime_min  
0   ["\nDuring her family's move to the suburbs, a...          125  
1   ['\nLion prince Simba and his father are targe...           88  
2   ['\nA young boy and his little sister struggle...           89  
3   ['\nTwo strangers find themselves linked in a ...          106  
4   ['\nTeen Miles Morales becomes the Spider-Man ...          117  
..                                                ...          ...  
80  ["\nTo everyone's surprise, including his own,...           92  
81  ["\nTo save her father from death in the army,...           88  
82  ["\nA mermaid princess makes a Faustian bargai...           83  
83  ['\nBagheera the Panther and Baloo the Bear ha...           78  
84  ['\nExiled into the dangerous forest by her wi...           83  

[85 rows x 11 columns]

1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [232]:
import numpy as np
A = np.array([[1, -2, 4], [2, 0, -1]])
B = np.array([[5, 2, 3], [4, 6, 2]])

In [233]:
A + B

array([[6, 0, 7],
       [6, 6, 1]])

In [234]:
A - B

array([[-4, -4,  1],
       [-2, -6, -3]])

2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [238]:
A = np.array([[1, 2], [2, -1], [3, 0]])
B = np.array([[-1, 1],[1, 2],[0, 0]])
C = A-3*B
C

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

3. Вычислите С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [239]:
A = np.array([[1, -1], [2, 0], [3, 0]])
B = np.array([[1, 1],[2, 0]])
C = A@B
C

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [249]:
from scipy import linalg
A = np.array([[6, -1, 4], [2, 1, 10], [8, 0, 2]])

np.linalg.det(A)

-95.99999999999999

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [253]:
A = np.array([[3, 3, -1], [4, 1, 3], [1, -2, -2]])
np.linalg.inv(A)

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])